on: [push]
name: Test
jobs:
  readmeExample:
    name: "[TEST] README example"
    runs-on: ubuntu-latest
    steps:

      - uses: octokit/request-action@v1.x
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/:owner/:repo/deployments
          mediaType: '{"previews": ["ant-man"]}'
          ref: "${{ github.ref }}"
          required_contexts: "[]"
      - run: "echo created deployment: '${{ steps.get_latest_release.outputs.data }}'"
      
      # Parse steps.create_check_run.outputs.data, since it is a string
      - id: parse_create_deployment
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.create_deployment.outputs.data }}
          id: "id"
          
      # Update check run to completed, succesful status
      - uses: octokit/request-action@v1.x
        id: update_deployment
        with:
          route: POST /repos/:owner/:repo/deployments/:deployment_id/statuses
          mediaType: '{"previews": ["flash-preview", "ant-man"]}'
          state: "success"
          deployment_id: "${{ steps.parse_create_deployment.outputs.id }}"
          log_url: "https://github.com/imjohnbo/request-action/actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
